import { ReactNode } from 'react';
import "@/src/styles/globals.css";
import {Providers} from "@/src/app/providers";
import { CustomToastProvider } from '../components/ui/toast';

export const metadata = {
  title: "Hair Talk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CustomToastProvider>
          {children}
          </CustomToastProvider>
          </Providers>
      </body>
    </html>
  );
}
